import pandas as pd

# Read the CSV file
df = pd.read_csv('/home/kaizen/Documents/SOD_EOD/SOD_EOD_System_Monitoring.csv', encoding='ISO-8859-1')

#HML Template
htmlHead = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sample HTML with CSS</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        table {
            width: 50%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid black;
        }
            th, td {
                padding: 8px;
                text-align: left;
            }
            th {
                background-color: #31ff48;
            }
        p span {
            color: red; 
        }
    </style>
</head>
<body>
    <p>Hi Team,</p>
    <p></p>
    <p>System monitoring report is ready! Please find it attached.</p>
    <table>
        <thead>
            <tr style="text-align: right;">
                <th>Infrastructure Segment</th>
                <th>Details</th>
                <th>Time</th>
                <th>Checked by</th>
                <th>Status (Up/Down)</th>
            </tr>
        </thead>
        <tbody>
"""
htmlTableEnd = "      </tbody>\n    </table>\n"
htmlNote = "    <p><span>Note:</span> This is an autogenerated email. If you have any questions, contact us at enterprise.server@pds.com.ph</p>\n"
htmlFooter = "</body>\n</html>"
# Combine the variables and insert data
html_content = htmlHead 
for i, row in df.iterrows():
    if i >= 57 and i <= 71:
        html_content += "           <tr>\n" 
        for item in row:
            status = row['Status (Up/Down)']
            if status != "UP" and item == row[4]:
                html_content += '               <th style="background-color: #ff3131;">{}</th>\n'.format(item)
            else: 
                html_content += '               <th>{}</th>\n'.format(item) 
        html_content += "           </tr>\n" 
html_content += htmlTableEnd 
html_content += htmlNote
html_content += htmlFooter 

# Save the HTML table to a file
with open('ebody.html', 'w', encoding='ISO-8859-1') as file:
    file.write(html_content)

