[Switch Configuration Begin : 0]
SwitchName = PDS-DS6610-SW1
Fabric ID = 128

[Boot Parameters]
boot.name:PDS-DS6610-SW1
boot.ipa:192.168.166.13
boot.mac:10:00:38:ba:b0:4d:f1:c0
boot.device:eth0
boot.gateway.ipa:192.168.166.1

[Configuration]
Custom.index:3
POD.reservations.base:0, 2, 4, 6
acl.clear:0
ag.fporttrunking:0
ag.port.nfportfailback:0x0
ag.port.nfportfailover:0x0
alpaList:1
auth.policy:0
auth.policy.dev:3
cer.internal_port_code:1
cfgtest.switch:1
fabric.domain:1
fabric.dport.onDemand:0
fabric.dynamic_dport_feature:1
fabric.ficonmode:0
fabric.fidcheckdisable:0
fabric.hifmode:0
fabric.ididmode:0
fabric.name:
fabric.npivProbeMode:0
fabric.nport_10bit_upd_scn:1
fabric.ops.BBCredit:16
fabric.ops.E_D_TOV:2000
fabric.ops.R_A_TOV:10000
fabric.ops.bladeFault_on_hwErrlevel:0
fabric.ops.dataFieldSize:2112
fabric.ops.max_hops:7
fabric.ops.mode.fcpProbeDisable:0
fabric.ops.mode.isolate:0
fabric.ops.mode.longDistance:0
fabric.ops.mode.noClassF:0
fabric.ops.mode.pidFormat:1
fabric.ops.mode.tachyonCompat:0
fabric.ops.mode.unicastOnly:0
fabric.ops.mode.useCsCtl:0
fabric.ops.vc.class.2:2
fabric.ops.vc.class.3:3
fabric.ops.vc.config:0xc0
fabric.ops.vc.linkCtrl:0
fabric.ops.vc.multicast:7
fabric.ops.wan_tov:0
fabric.pdidModeDisable:0
fabric.principalSwSelMode:0
fabric.rdp_poll_cycle:0
fabric.remoteFosexec:0
fabric.wwnPidMode:0
fc4.fcp.productId:DS-6610B
fc4.fcp.vendorId:DELL
fcAL.alwaysSendRSCN:0
fcAL.fanFrameDisable:0
fcAL.openSendCLS:4
fcAL.useAltBBCredit:0
fdd.acceptcfg.auth:1
fdd.acceptcfg.dcc:1
fdd.acceptcfg.fcs:1
fdd.acceptcfg.ipf:1
fdd.acceptcfg.pwd:1
fdd.acceptcfg.scc:1
fdd.fabwidecfg:
fdd.hash.dcc:0
fdd.hash.fbw:0
fdd.hash.fcs:0
fdd.hash.pwd:0
fdd.hash.scc:0
fdd.hashpresent.dcc:0
fdd.hashpresent.fbw:0
fdd.hashpresent.fcs:0
fdd.hashpresent.pwd:0
fdd.hashpresent.scc:0
featuredb.status:0
ficu.DHBsize:0
ficu.EBCDICcodePage:37
ficu.MIHPTO:180
ficu.faf.hdata:0
ficu.faf.keyctr:0
ficu.faf.modereg:0
ficu.fmsmode:0
flannel.ops.frameColMethod:piling
flannel.ops.openBBCredit:4
flow.ioanalytics:0
gen.fabos:0
gen.zone:0
http.BoundApplication:
ms.PlatEnable:0
ms.TDEnable:0
ms.TolerantFBEnabled:0
np.feature.gen.ctrl.flag:0
np.feature.gen.ctrl.pattern:0
np.feature.gen.ctrl.size:0
np.feature.mirror.ctrl.flag:0
np.feature.mirror.ctrl.numframes:0
np.feature.mirror.ctrl.wraplog:0
np.meta.devaddrmode:0
np.meta.entityaddrmode:0
np.meta.nflows:0
np.meta.portaddrmode:0
np.meta.predefver:0
np.meta.simport:0
np.meta.totalflows:0
np.meta.v2.nflows:0
np.meta.v3.nflows:0
np.meta.v4.nflows:0
np.meta.v5.nflows:0
np.meta.v7.nflows:0
np.meta.ver:0
ns.DomRscnToDevForSwChg.enable:0
ns.EndDeviceRscnFormat:1
oemLogo:0
perf.framemon.enabled:0
perf.framemon.names:scsi,scsiread,scsiwrite,scsirw,scsi2reserve,scsi3reserve,ip,abts,baacc
perf.framemon.num:9
perf.framemonc.abts:0|4,0xFF,0x81;12,0xFF,0x0;|0||
perf.framemonc.baacc:0|4,0xFF,0x84;12,0xFF,0x00;|0||
perf.framemonc.ip:0|12,0xFF,0x05;|0||
perf.framemonc.scsi:0|12,0xFF,0x08;|0||
perf.framemonc.scsi2reserve:0|12,0xFF,0x08;4,0xFF,0x06;40,0xFF,0x16,0x56;|0||
perf.framemonc.scsi3reserve:0|12,0xFF,0x08;4,0xFF,0x06;40,0xFF,0x5F;41,0xFF,0x01|0||
perf.framemonc.scsiread:0|12,0xFF,0x08;4,0xFF,0x06;40,0xFF,0x08,0x28;|0||
perf.framemonc.scsirw:0|12,0xFF,0x08;4,0xFF,0x06;40,0xFF,0x08,0x28,0x0A,0x2A;|0||
perf.framemonc.scsiwrite:0|12,0xFF,0x08;4,0xFF,0x06;40,0xFF,0x0A,0x2A;|0||
portNpivLimit:
quickLoop.holdOpenInit:0
quickLoop.noAlpaZero:0
quickLoop.peerWWN:00:00:00:00:00:00:00:00
quickLoop.portBitmap:0x0000000000000000
quickLoop.softInit:0
rasm.filter:5
rlsDisable:1
route.delayReroute:0
route.embeddedPortBcast:1
route.lossless:1
route.stickyRoutes:0
rte.external_policy:3
rte.intCostFactor:100
rte.internal_policy:0
sec.fstov:5000
sec.mode:0
sec.versioStamp:
sec.versionStamp:0
shell.delete:0
shell.quiet:0
sigmad.cfs:0x0
switch.defaultPortname:0
switch.domain_id_offset:96
switch.dynamicPortname:0
switch.edgeHoldTime:220
switch.fdmiHostname:0
switch.interopMode:0
switch.largeEntry.cap:0
switch.login.enforce_login:0
switch.login.flogisPerSec:0
switch.login.freeFdiscs:0
switch.login.max_flogi_count:100
switch.login.perSwitchMax:28800
switch.login.stageInterval:0
switch.mcdtDefaultZone:0
switch.mcdtFabricMode:0
switch.mcdtSafeZone:0
switch.xisluse:0
thresh.alarmsfilter:1
ts.clockServer:LOCL
ts.clockServerAuthSpec:0
ts.clockServerIndex:-1
ts.clockServerIndexList:-1
ts.clockServerLegacyMode:1
ts.clockServerList:LOCL
ucid.trace.level:6
xlativeModeDisable:0
zoning.FabLockTimeout:5
zoning.check.nodeNameDisabled:0
zoning.conOpenTransDet:1
zoning.standardMode:0

[NP Configuration]
np.meta.ver:2
np.meta.nflows:0
np.meta.v2.nflows:0
np.meta.v3.nflows:1
np.meta.v4.nflows:1
np.meta.v5.nflows:0
np.meta.v7.nflows:1
np.meta.totalflows:3
np.meta.predefver:6
np.meta.devaddrmode:0
np.meta.portaddrmode:0
np.meta.entityaddrmode:0
np.feature.gen.ctrl.flag:12
np.feature.gen.ctrl.size:2048
np.feature.gen.ctrl.pattern:
np.feature.mirror.ctrl.flag:3
np.feature.mirror.ctrl.numframes:0
np.feature.mirror.ctrl.wraplog:0
np.flow.def.v2.name.0:sys_gen_all_simports
np.flow.def.config.v2.state.0:4
np.flow.feature.stats.v2.state.0:0
np.flow.feature.gen.v2.state.0:1
np.flow.feature.latency.v2.state.0:0
np.flow.feature.mirror.v2.state.0:0
np.flow.def.v2.userbitmap.0:15728640
np.flow.def.v2.devaddrmode.0:0
np.flow.def.v2.portaddrmode.0:0
np.flow.def.v2.entityaddrmode.0:0
np.flow.def.ver.0:2
np.flow.def.v2.predefined.0:1
np.flow.def.v2.sid.0:ffffffff
np.flow.def.v2.did.0:ffffffff
np.flow.def.v2.txport.0:255,*-255,0
np.flow.def.v2.rxport.0:255,*-255,0
np.flow.feature.gen.ctrl.v2.size.0:0
np.flow.feature.gen.ctrl.v2.pattern.0:
np.flow.feature.stats.ctrl.v2.flag.0:0
np.flow.feature.mirror.ctrl.v2.numframes.0:0
np.flow.feature.mirror.ctrl.numframes.0:0
np.flow.def.v3.name.1:sys_analytics_vtap
np.flow.def.config.v3.state.1:4
np.flow.feature.stats.v3.state.1:0
np.flow.feature.gen.v3.state.1:0
np.flow.feature.latency.v3.state.1:0
np.flow.feature.mirror.v3.state.1:1
np.flow.def.v3.userbitmap.1:1078034432
np.flow.def.v3.devaddrmode.1:0
np.flow.def.v3.portaddrmode.1:0
np.flow.def.v3.entityaddrmode.1:0
np.flow.def.v3.ver.1:3
np.flow.def.v3.predefined.1:1
np.flow.def.v3.rxport.1:255,*-255,0
np.flow.def.v3.scsicmd.1:36
np.flow.feature.gen.ctrl.v3.size.1:0
np.flow.feature.gen.ctrl.v3.pattern.1:
np.flow.feature.stats.ctrl.v3.flag.1:0
np.flow.feature.mirror.ctrl.v3.numframes.1:0
np.flow.feature.mirror.ctrl.numframes.1:0
np.flow.def.v7.name.2:sys_flow_monitor
np.flow.def.config.v7.state.2:4
np.flow.feature.stats.v7.state.2:3
np.flow.feature.gen.v7.state.2:0
np.flow.feature.latency.v7.state.2:0
np.flow.feature.mirror.v7.state.2:0
np.flow.def.v7.userbitmap.2:35184379428864
np.flow.def.v7.devaddrmode.2:0
np.flow.def.v7.portaddrmode.2:0
np.flow.def.v7.entityaddrmode.2:0
np.flow.def.v7.ver.2:7
np.flow.def.v7.predefined.2:1
np.flow.def.v7.sid.2:ffffffff
np.flow.def.v7.did.2:ffffffff
np.flow.def.v7.rxport.2:255,*-255,0
np.flow.feature.gen.ctrl.v7.size.2:0
np.flow.feature.gen.ctrl.v7.pattern.2:
np.flow.feature.stats.ctrl.v7.flag.2:0
np.flow.feature.stats.ctrl.v7.vmmode.2:0
np.flow.feature.stats.ctrl.v7.flowage.2:0
np.flow.feature.stats.ctrl.v7.itReserve.2:0
np.flow.feature.mirror.ctrl.v7.numframes.2:0
np.flow.feature.mirror.ctrl.numframes.2:0

[Zoning]
cfg.DS6610-SW1-cfg:PDSNG-ESXi-1-HBA1-Unity-XT380F-SPA0;PDSNG-ESXi-2-HBA1-Unity-XT380F-SPA0
zone.PDSNG-ESXi-1-HBA1-Unity-XT380F-SPA0:PDSNG-ESXi-1-HBA1;Unity-XT380F-SPA0;Unity-XT380F-SPB0
zone.PDSNG-ESXi-2-HBA1-Unity-XT380F-SPA0:PDSNG-ESXi-2-HBA1;Unity-XT380F-SPA0;Unity-XT380F-SPB0
alias.PDSNG-ESXi-1-HBA1:10:00:70:b7:e4:0f:18:81
alias.PDSNG-ESXi-2-HBA1:10:00:70:b7:e4:0f:18:9f
alias.Unity-XT380F-SPA0:50:06:01:62:4d:e0:30:2e
alias.Unity-XT380F-SPB0:50:06:01:6a:4d:e0:30:2e
defzone:allaccess
enable:DS6610-SW1-cfg

[Defined Security policies]

[Active Security policies]

[FICU SAVED FILES]

[VS_SW_CONF]
vs.hdr:01abcdef000000010000000000000068
vs.num_entries:0

[MAPS CONFIG DB]
maps.activePolicy:dflt_base_policy
maps.activePolicy.state:0
maps.enabled:1

[Banner]
--------------------------------------------------------------------------------------------
                                       ATTENTION
  It is recommended that you change the default passwords for all the switch accounts.
 Refer to the product release notes and administrators guide if you need further information.
 --------------------------------------------------------------------------------------------

[End]
[Switch Configuration End : 0]
