.TH "Neyt's Manual" "v1.0" "August 2024" "~/Script/" "Manual For Linux Workstation"
.SH CUSTOMIZED ALIASES 
 Different customized aliases for the worksation. Some of the aliases may thow an error if not configured properly inside the PDS Group local network or workstations.
.SH SYNOPSIS
.B rld \... 
.TP
.B Random 
 rld \- Reload the bash configuration. 
 usg \- Show the size of files and direcotories. 
 idate \- View the date inteactively. 
 l \- List,categorize dir/file and sort by time in Ascending order. 
 mm \- View customize manual page. 
.TP
.B Editing 
 vB \- bashrc file. 
 vBa \- Customize Alias.
 vBf \- Customize functions.
 vdf \- Forward Date Script for DR(Disaster Recovery) Activity. 
 vmm \- Main manual page. 
 vss \- SOD EOD Script file(SOD.sh)   
 vse \- SOD EOD Script file(edit_Csv_File.sh).
 vSk \- SSH Known hosts. 
 vSs \- Server list.
 vV \- .vimrc file.
 vs \- SOD_EOD_System_Monitoring.csv file.
.TP
.B Execute Scripts 
 rdfd \- Run DR(Disaster Recovery) Forward Date.
 rds \- Run Mirrorring Script(showDRStat.sh).
.TP
.B Change Directories 
 gGet \- Goto ~/trans/recieved
 gS \- Goto ~/Script 
 gSend \- Goto ~/trans/Send
.TP
.B Git Commands
 gl \- Short for "git log --online". 
 gs \- Short for "git status". 
.SH CUSTOMIZED FUNCTIONS 
 Different customized functions for the worksation. Some of the aliases may thow an error if not configured properly inside the PDS Group local network or workstations.
.SH SYNOPSIS
.B updateMan \... 
.SH DESCRIPTION 
updateMan is an instruction to udpate the custom manual page.
.SH AUTHOR
 Written by Christian Araña <christian.arana@pds.com.ph>

