.TH Neyt's_ Manual "August 2024" "v1.0" "Manual For Linux Workstation"
.SH Workstation Alias 
 l \- Shortcut key to list directory. 
.SH SYNOPSIS
.B example
[\-h] [\-\-help]
.SH DESCRIPTION
This is a simple example of how to write a Linux manual page.
.SH OPTIONS
.TP
.B \-h, \-\-help
Displays the help message.
.SH EXAMPLES
.B example \-h
.SH AUTHOR
Christian Araña <christian.arana@pds.com.ph>
.SH SEE ALSO
.B man(1)
This is a simple example of how to write a Linux manual page.
.SH OPTIONS
.TP
.B \-h, \-\-help
Displays the help message.
.SH EXAMPLES
.B example \-h
.SH AUTHOR
Your Name <your.email@example.com>
.SH SEE ALSO
.B man(1)

